apiVersion: certificates.k8s.io/v1
kind: Issuer
metadata:
  name: letsencrypt-pod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'shahabvalizade@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-pod
    http01: {}